"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "ar" | "es";

const translations: Record<string, Partial<Record<Language | "fr", string>>> = {
  "Home": { fr: "Accueil", ar: "الرئيسية" },
  "Menu": { fr: "Menu", ar: "القائمة" },
  "Our Story": { fr: "Notre histoire", ar: "قصتنا" },
  "Gallery": { fr: "Galerie", ar: "معرض الصور" },
  "Visit Us": { fr: "Nous visiter", ar: "زورونا" },
  "View Menu": { fr: "Voir le menu", ar: "عرض القائمة" },
  "Discover Our Menu": { fr: "Découvrir notre menu", ar: "اكتشف قائمتنا" },
  "Moroccan Specialty Coffee & Bakery": { fr: "Café de spécialité et boulangerie marocaine", ar: "قهوة مختصة ومخبوزات مغربية" },
  "Open navigation menu": { fr: "Ouvrir le menu de navigation", ar: "فتح قائمة التنقل" },
  "Close navigation menu": { fr: "Fermer le menu de navigation", ar: "إغلاق قائمة التنقل" },
  "Main Navigation": { fr: "Navigation principale", ar: "التنقل الرئيسي" },
  "Select language": { fr: "Choisir la langue", ar: "اختر اللغة" },
  "Hero Section": { fr: "Bannière principale", ar: "القسم الرئيسي" },
  "Where": { fr: "Là où", ar: "حيث" },
  "Elegance": { fr: "l’élégance", ar: "الأناقة" },
  "Meets Flavor": { fr: "rencontre la saveur", ar: "تلتقي بالنكهة" },
  "Artisan pastries, specialty coffee, and moments worth savoring.": { fr: "Pâtisseries artisanales, café de spécialité et instants à savourer.", ar: "حلويات حرفية وقهوة مختصة ولحظات تستحق الاستمتاع." },
  "Discover Our Story": { fr: "Découvrir notre histoire", ar: "اكتشف قصتنا" },
  "OUR STORY": { fr: "NOTRE HISTOIRE", ar: "قصتنا" },
  "Purpose.": { fr: "Intention.", ar: "بهدف." },
  "Crafted with": { fr: "Créé avec", ar: "صُنع بـ" },
  "Made to Be": { fr: "Fait pour être", ar: "صُنع لكي يُستمتع به" },
  "Savored.": { fr: "Savouré.", ar: "ويُذاق." },
  "Signature Selection": { fr: "Sélection signature", ar: "تشكيلة مميزة" },
  "Bakery": { fr: "Boulangerie", ar: "مخبوزات" },
  "Pastry": { fr: "Pâtisserie", ar: "حلويات" },
  "Desserts": { fr: "Desserts", ar: "حلويات" },
  "Freshly Baked": { fr: "Fraîchement cuits", ar: "مخبوزات طازجة" },
  "Signature Pastries": { fr: "Pâtisseries signature", ar: "حلوياتنا المميزة" },
  "Fine Desserts": { fr: "Desserts raffinés", ar: "حلويات راقية" },
  "Golden layers and flaky pastries, baked fresh in-house every morning.": { fr: "Des feuilletages dorés et croustillants, préparés chaque matin sur place.", ar: "طبقات ذهبية ومعجنات هشة تُخبز طازجة كل صباح في المخبز." },
  "Made slowly. Finished with intention. An elegant touch to your day.": { fr: "Préparées avec patience et soin, pour apporter une touche d’élégance à votre journée.", ar: "تُحضّر على مهل وتُقدّم بعناية لتضيف لمسة أنيقة إلى يومك." },
  "A final touch worth staying for — beautiful, seasonal, made with care.": { fr: "Une dernière douceur qui mérite de s’attarder : de saison et préparée avec soin.", ar: "لمسة أخيرة تستحق البقاء؛ جميلة وموسمية ومُحضّرة بعناية." },
  "Explore": { fr: "Découvrir", ar: "اكتشف" },
  "View Full Menu": { fr: "Voir tout le menu", ar: "عرض القائمة كاملة" },
  "Our Menu": { fr: "Notre menu", ar: "قائمتنا" },
  "Desserts Menu": { fr: "Menu des desserts", ar: "قائمة الحلويات" },
  "A sweeter side of AlArak": { fr: "La douceur signée AlArak", ar: "الجانب الأكثر حلاوة من الأراك" },
  "Cakes & Pastries": { fr: "Gâteaux et pâtisseries", ar: "كعك ومعجنات" },
  "Trompe L'Œil Desserts": { fr: "Desserts trompe-l’œil", ar: "حلويات بتصميم يخدع العين" },
  "Cookies": { fr: "Biscuits", ar: "بسكويت" },
  "Chocolate Mousse Cake": { fr: "Gâteau mousse au chocolat", ar: "كعكة موس الشوكولاتة" },
  "Carrot Cake": { fr: "Gâteau aux carottes", ar: "كعكة الجزر" },
  "Tiramisu": { fr: "Tiramisu", ar: "تيراميسو" },
  "Opera Cake": { fr: "Gâteau Opéra", ar: "كعكة أوبرا" },
  "Sacher Cake": { fr: "Gâteau Sacher", ar: "كعكة زاخَر" },
  "Pistachio Vanilla Cake": { fr: "Gâteau pistache et vanille", ar: "كعكة الفستق والفانيليا" },
  "Rocher Cake": { fr: "Gâteau Rocher", ar: "كعكة روشيه" },
  "Almond Cake": { fr: "Gâteau aux amandes", ar: "كعكة اللوز" },
  "Lemon Cheesecake": { fr: "Cheesecake au citron", ar: "تشيز كيك بالليمون" },
  "Profiteroles": { fr: "Profiteroles", ar: "بروفيتيرول" },
  "Coffee Bean Trompe L'Œil": { fr: "Trompe-l’œil grain de café", ar: "حلوى بشكل حبة قهوة" },
  "Mango Trompe L'Œil": { fr: "Trompe-l’œil mangue", ar: "حلوى بشكل مانجو" },
  "Strawberry Trompe L'Œil": { fr: "Trompe-l’œil fraise", ar: "حلوى بشكل فراولة" },
  "Chocolate Chip Cookie": { fr: "Cookie aux pépites de chocolat", ar: "كوكيز برقائق الشوكولاتة" },
  "Oat Cookies": { fr: "Biscuits à l’avoine", ar: "بسكويت الشوفان" },
  "Coconut Cookies": { fr: "Biscuits à la noix de coco", ar: "بسكويت جوز الهند" },
  "Cantucci": { fr: "Cantucci", ar: "كانتو تشيني" },
  "Matcha Cookies": { fr: "Biscuits au matcha", ar: "بسكويت الماتشا" },
  "Dark Chocolate Cookies": { fr: "Biscuits au chocolat noir", ar: "بسكويت الشوكولاتة الداكنة" },
  "Something sweet awaits": { fr: "Une douceur vous attend", ar: "حلوى لذيذة بانتظارك" },
  "Come taste it for yourself.": { fr: "Venez goûter par vous-même.", ar: "تعالوا لتتذوقوا بأنفسكم." },
  "Visit Alarak →": { fr: "Visiter Alarak →", ar: "زوروا الأراك ←" },
  "Our Gallery": { fr: "Notre galerie", ar: "معرضنا" },
  "Atmosphere & moments": { fr: "Ambiance et instants", ar: "أجواء ولحظات" },
  "Gallery photos": { fr: "Photos de la galerie", ar: "صور المعرض" },
  "Photo coming soon": { fr: "Photo à venir", ar: "الصورة قريباً" },
  "View photo": { fr: "Voir la photo", ar: "عرض الصورة" },
  "Close photo viewer": { fr: "Fermer la photo", ar: "إغلاق الصورة" },
  "Previous photo": { fr: "Photo précédente", ar: "الصورة السابقة" },
  "Next photo": { fr: "Photo suivante", ar: "الصورة التالية" },
  "The craft story": { fr: "L’histoire du savoir-faire", ar: "قصة الحرفة" },
  "Close viewer": { fr: "Fermer", ar: "إغلاق" },
  "Share your Alarak moments": { fr: "Partagez vos instants Alarak", ar: "شاركوا لحظاتكم مع الأراك" },
  "Tag ": { fr: "Identifiez-nous : ", ar: "أشيروا إلينا: " },
  "Visit & taste": { fr: "Visiter et déguster", ar: "زوروا وتذوقوا" },
  "Experience Alarak in person": { fr: "Vivez l’expérience Alarak", ar: "عِش تجربة الأراك" },
  "Daily": { fr: "Tous les jours", ar: "يومياً" },
  "Crafting Moments of Pure Warmth &": { fr: "Des instants de douceur et de", ar: "نصنع لحظات من الدفء و" },
  "Artisan Mastery in Fnideq": { fr: "L'artisanat a Fnideq", ar: "حرفية متقنة في الفنيدق" },
  "Artisan precision": { fr: "Précision artisanale", ar: "حرفية دقيقة" },
  "The Art of ": { fr: "L’art de ", ar: "فن " },
  "Slow Crafting": { fr: "prendre son temps", ar: "الصنع على مهل" },
  "Fresh pastries": { fr: "Pâtisseries fraîches", ar: "معجنات طازجة" },
  "Baked each morning in Fnideq": { fr: "Cuites chaque matin a Fnideq", ar: "تُخبز كل صباح في الفنيدق" },
  "Specialty coffee": { fr: "Café de spécialité", ar: "قهوة مختصة" },
  "Single-origin beans, carefully brewed": { fr: "Grains d’origine unique, préparés avec soin", ar: "حبوب من مصدر واحد تُحضّر بعناية" },
  "Handcrafted perfection": { fr: "La perfection artisanale", ar: "إتقان يدوي" },
  "Fresh berry tartlets, made daily": { fr: "Tartelettes aux fruits rouges, préparées chaque jour", ar: "تارت التوت الطازج، يُحضّر يومياً" },
  "The Alarak philosophy": { fr: "La philosophie Alarak", ar: "فلسفة الأراك" },
  "Warm hospitality": { fr: "Hospitalité chaleureuse", ar: "ضيافة دافئة" },
  "A welcome that feels like home": { fr: "Un accueil comme à la maison", ar: "ترحيب يشعرك بأنك في بيتك" },
  "Our vision": { fr: "Notre vision", ar: "رؤيتنا" },
  "An Elegant Refuge in ": { fr: "Un refuge élégant au", ar: "ملاذ أنيق في" },
  "the Heart of Fnideq": { fr: "au coeur de Fnideq", ar: "قلب الفنيدق" },
  "Come share a moment with us.": { fr: "Venez partager un moment avec nous.", ar: "تعالوا وشاركونا لحظة جميلة." },
  "Good coffee, thoughtful pastries, and a warm welcome in Fnideq.": { fr: "Un bon cafe, des patisseries soignees et un accueil chaleureux a Fnideq.", ar: "قهوة طيبة ومعجنات متقنة وترحيب دافئ في الفنيدق." },
  "Explore the menu": { fr: "Découvrir le menu", ar: "اكتشفوا القائمة" },
  "Visit our boutique": { fr: "Visitez notre boutique", ar: "زوروا متجرنا" },
  "Experience ALARAK In Person": { fr: "Découvrez ALARAK en personne", ar: "عِش تجربة الأراك بنفسك" },
  "Join us in Fnideq for exceptional coffee, fresh pastries, and an atmosphere designed for relaxation.": { fr: "Retrouvez-nous a Fnideq pour un cafe d'exception, des patisseries fraiches et une atmosphere propice a la detente.", ar: "زورونا في الفنيدق لقهوة مميزة ومعجنات طازجة وأجواء مريحة." },
  "Location": { fr: "Adresse", ar: "الموقع" },
  "Fnideq": { fr: "Fnideq", ar: "الفنيدق" },
  "Morocco": { fr: "Maroc", ar: "المغرب" },
  "Opening Hours": { fr: "Horaires", ar: "ساعات العمل" },
  "Monday – Sunday": { fr: "Lundi – dimanche", ar: "الإثنين – الأحد" },
  "Contact": { fr: "Contact", ar: "اتصلوا بنا" },
  "Our Location": { fr: "Notre adresse", ar: "موقعنا" },
  "Phone": { fr: "Téléphone", ar: "الهاتف" },
  "Come by,": { fr: "Passez nous voir,", ar: "زورونا،" },
  "stay awhile.": { fr: "prenez le temps.", ar: "وأمضوا وقتاً جميلاً." },
  "We'd love to welcome you to Alarak. Enjoy our coffee, fresh pastries and handcrafted cakes in a warm and relaxed atmosphere.": { fr: "Nous serons ravis de vous accueillir chez Alarak. Savourez notre café, nos pâtisseries fraîches et nos gâteaux artisanaux dans une ambiance chaleureuse et détendue.", ar: "يسعدنا استقبالكم في الأراك. استمتعوا بقهوتنا ومعجناتنا الطازجة وكعكاتنا المصنوعة يدوياً في أجواء دافئة ومريحة." },
  "Get Directions": { fr: "Itinéraire", ar: "الاتجاهات" },
  "Contact Us": { fr: "Contactez-nous", ar: "تواصلوا معنا" },
  "Fnideq, Morocco": { fr: "Fnideq, Maroc", ar: "الفنيدق، المغرب" },
  "Send a message": { fr: "Envoyer un message", ar: "أرسل رسالة" },
  "Have a question? Send us a note and we'll get back to you.": { fr: "Une question ? Écrivez-nous, nous vous répondrons.", ar: "لديك سؤال؟ أرسل لنا رسالة وسنعاود التواصل معك." },
  "Your email address": { fr: "Votre adresse e-mail", ar: "بريدك الإلكتروني" },
  "Write your message...": { fr: "Écrivez votre message…", ar: "اكتب رسالتك..." },
  "Send message": { fr: "Envoyer le message", ar: "إرسال الرسالة" },
  "Your email app will open with the message ready to send.": { fr: "Votre application e-mail s’ouvrira avec le message prêt à être envoyé.", ar: "سيفتح تطبيق البريد الإلكتروني والرسالة جاهزة للإرسال." },
  "Follow": { fr: "Suivre", ar: "تابعونا" },
  "Instagram": { fr: "Instagram", ar: "إنستغرام" },
  "Reservations via Instagram": { fr: "Réservations sur Instagram", ar: "الحجوزات عبر إنستغرام" },
  "Back to top": { fr: "Retour en haut", ar: "العودة إلى الأعلى" },
  "Follow Alarak on Instagram": { fr: "Suivre Alarak sur Instagram", ar: "تابعوا الأراك على إنستغرام" },
  "Follow Alarak on Facebook": { fr: "Suivre Alarak sur Facebook", ar: "تابعوا الأراك على فيسبوك" },
  "Follow Alarak on TikTok": { fr: "Suivre Alarak sur TikTok", ar: "تابعوا الأراك على تيك توك" },
  "Follow Alarak on YouTube": { fr: "Suivre Alarak sur YouTube", ar: "تابعوا الأراك على يوتيوب" },

  "Alarak Founder & Master Artisan": { fr: "Fondateur et ma?tre artisan Alarak", ar: "مؤسس الأراك وحرفي ماهر" },
  "ALARAK was born from a deep love of craft ? where the art of specialty coffee meets the warmth of Moroccan hospitality. Every cup is brewed with intention, every pastry shaped by the hands of artisans who believe that food is a form of care.": { fr: "ALARAK est n? d?un profond amour du savoir-faire, l? o? le caf? de sp?cialit? rencontre la chaleur de l?hospitalit? marocaine. Chaque tasse est pr?par?e avec intention et chaque p?tisserie fa?onn?e par des artisans passionn?s.", ar: "وُلد الأراك من حب عميق للحرفة، حيث تلتقي القهوة المختصة بدفء الضيافة المغربية. نحضّر كل كوب بعناية ونصنع كل معجنة بيد حرفية." },
  "We create spaces and flavors that invite you to slow down, to savor, and to feel genuinely welcomed. This is not just a caf? ? it is a moment worth returning to.": { fr: "Nous cr?ons des lieux et des saveurs qui invitent ? ralentir, ? savourer et ? se sentir accueilli. Plus qu?un caf?, c?est un moment auquel on aime revenir.", ar: "نبتكر مساحات ونكهات تدعوك للهدوء والتذوق والشعور بالترحيب. ليس مقهى فحسب، بل لحظة تستحق العودة." },
  "Coffee and pastry are not simply served ? they are shared moments of genuine warmth.": { fr: "Le caf? et les p?tisseries ne se servent pas seulement : ils se partagent dans un moment de chaleur sinc?re.", ar: "ليست القهوة والمعجنات مجرد طعام وشراب، بل لحظات دافئة نتشاركها." },
  "A visual journey through artisanal craft, warm ambience, and specialty coffee in Fnideq. Every corner is made for slowing down and savoring the moment.": { fr: "Un voyage au coeur du savoir-faire artisanal, d?une ambiance chaleureuse et du cafe de specialite a Fnideq. Chaque recoin invite a savourer l?instant.", ar: "رحلة بصرية بين الحرفة الأصيلة والأجواء الدافئة والقهوة المختصة في الفنيدق." },
  "Dessert categories": { fr: "Cat?gories de desserts", ar: "أصناف الحلويات" },
  "View on Maps": { fr: "Voir sur la carte", ar: "عرض على الخريطة" },
  "Open Fnideq on Google Maps": { fr: "Ouvrir Fnideq dans Google Maps", ar: "افتح الفنيدق على خرائط جوجل" },
  "Whether you're stopping in for your morning coffee or meeting friends over something sweet, we hope each visit becomes a small ritual worth returning to.": { fr: "Que vous passiez pour votre caf? du matin ou retrouviez des amis autour d?une douceur, nous esp?rons que chaque visite deviendra un rituel auquel revenir.", ar: "سواء مررتم لقهوة الصباح أو للقاء الأصدقاء مع حلوى، نأمل أن تصبح كل زيارة عادة جميلة تعودون إليها." },
  "Specialty coffee and artisan pastry, made slowly in Fnideq — a warm place to pause, savor, and return to.": { fr: "Cafe de specialite et patisseries artisanales prepares avec soin a Fnideq, dans un lieu chaleureux ou faire une pause et savourer l?instant.", ar: "قهوة مختصة ومعجنات يدوية تُحضّر بعناية في الفنيدق، في مكان دافئ للاستراحة والتذوق." },
  "Find us in Fnideq for specialty coffee, freshly baked pastries, and a warm place to pause.": { fr: "Retrouvez-nous a Fnideq pour un cafe de specialite, des patisseries fraiches et une pause chaleureuse.", ar: "تفضلوا بزيارتنا في الفنيدق للاستمتاع بالقهوة المختصة والمعجنات الطازجة في أجواء دافئة." },
};



Object.assign(translations, {
  "CAREER & TRAINING": { fr: "PARCOURS & FORMATION", ar: "المسار والتكوين" },
  "From New York, a craft brought home.": { fr: "De New York, un savoir-faire rapporté au pays.", ar: "من نيويورك، حرفة عاد بها إلى الوطن." },
  "At the Institute of Culinary Education in New York, Abdellah El Idrissi completed two intensive programs: 720 hours in Culinary Arts, followed by 600 hours in Pastry & Baking Arts. He graduated with Highest Honors in 2016 and 2018, then brought his craft and experience home to Morocco.": {
    fr: "À l’Institute of Culinary Education de New York, Abdellah El Idrissi a suivi deux formations intensives : 720 heures en arts culinaires, puis 600 heures en pâtisserie et boulangerie. Il a obtenu les plus hautes distinctions en 2016 et 2018 avant de rapporter son savoir-faire au Maroc.",
    ar: "أكمل عبد الله الإدريسي في معهد Institute of Culinary Education بنيويورك برنامجين مكثفين: 720 ساعة في فنون الطهي، تلتها 600 ساعة في فنون الحلويات والخبز. وتخرج بمرتبة الشرف العليا عامي 2016 و2018، ثم عاد بخبرته إلى المغرب.",
  },
  "Hours of training": { fr: "Heures de formation", ar: "ساعة تدريب" },
  "Highest Honors": { fr: "Très hautes distinctions", ar: "مرتبة الشرف العليا" },
  "Graduated with": { fr: "Diplômé avec", ar: "تخرج بمرتبة" },
  "New York, USA": { fr: "New York, États-Unis", ar: "نيويورك، الولايات المتحدة" },
  "Institute of Culinary Education": { fr: "Institute of Culinary Education", ar: "معهد Institute of Culinary Education" },
  "Pastry & Baking Arts · 2018": { fr: "Arts de la pâtisserie et boulangerie · 2018", ar: "فنون الحلويات والخبز · 2018" },
  "Total training hours": { fr: "Heures de formation au total", ar: "إجمالي ساعات التدريب" },
  "Culinary Arts Diploma": { fr: "Diplôme en arts culinaires", ar: "دبلوم فنون الطهي" },
  "Pastry & Baking Arts Diploma": { fr: "Diplôme en pâtisserie et boulangerie", ar: "دبلوم فنون الحلويات والخبز" },
  "Intensive training in cooking, nutrition, food preparation, and culinary techniques at the Institute of Culinary Education in New York. Graduated with Highest Honors.": {
    fr: "Formation intensive en cuisine, nutrition, préparation des aliments et techniques culinaires à l’Institute of Culinary Education de New York. Diplômé avec les plus hautes distinctions.",
    ar: "تدريب مكثف في الطهي والتغذية وتحضير الطعام وتقنيات فنون الطهي في معهد Institute of Culinary Education بنيويورك. تخرج بمرتبة الشرف العليا.",
  },
  "Intensive training in pastry, baking, dessert production, and confectionery arts at the Institute of Culinary Education in New York. Graduated with Highest Honors.": {
    fr: "Formation intensive en pâtisserie, boulangerie, desserts et confiserie à l’Institute of Culinary Education de New York. Diplômé avec les plus hautes distinctions.",
    ar: "تدريب مكثف في الحلويات والخبز وإعداد الحلويات وفنون السكر في معهد Institute of Culinary Education بنيويورك. تخرج بمرتبة الشرف العليا.",
  },
  "Graduated with Highest Honors": { fr: "Diplômé avec les plus hautes distinctions", ar: "تخرج بمرتبة الشرف العليا" },
  "Two ICE diplomas": { fr: "Deux diplômes ICE", ar: "شهادتا ICE" },
  "Culinary Arts · 2016": { fr: "Arts culinaires · 2016", ar: "فنون الطهي · 2016" },
  "Abdellah El Idrissi's culinary arts diploma": {
    fr: "Diplôme d’Abdellah El Idrissi en arts culinaires",
    ar: "دبلوم عبد الله الإدريسي في فنون الطهي",
  },
  "Abdellah El Idrissi's pastry and baking arts diploma": {
    fr: "Diplôme d’Abdellah El Idrissi en pâtisserie et arts de la boulangerie",
    ar: "دبلوم عبد الله الإدريسي في فنون الحلويات والخبز",
  },
  "View more about Abdellah's career": {
    fr: "En savoir plus sur le parcours d’Abdellah",
    ar: "اكتشف المزيد عن مسيرة عبد الله",
  },
  "My journey into the world of culinary arts and pastry began with a passion for craftsmanship, creativity, and attention to detail.": {
    fr: "Mon parcours dans les arts culinaires et la pâtisserie est né d’une passion pour le savoir-faire, la créativité et le souci du détail.",
    ar: "بدأت رحلتي في عالم فنون الطهي والحلويات بشغف للحرفية والإبداع والاهتمام بالتفاصيل.",
  },
  "This journey led me to New York, where I earned my diploma from the Institute of Culinary Education in Culinary Arts and Pastry Arts.": {
    fr: "Ce parcours m’a conduit à New York, où j’ai obtenu mon diplôme en arts culinaires et en pâtisserie à l’Institute of Culinary Education.",
    ar: "قادني هذا الشغف إلى نيويورك، حيث حصلت على دبلوم فنون الطهي والحلويات من معهد Institute of Culinary Education.",
  },
  "And that dream became": { fr: "Et ce rêve est devenu", ar: "وهكذا أصبح ذلك الحلم" },
  "Alarak Coffee & Bakery.": { fr: "Alarak Coffee & Bakery.", ar: "الأراك للقهوة والمخبوزات." },
  "Explore our": { fr: "Découvrir notre", ar: "اكتشف" },
  "Explore": { fr: "Découvrir", ar: "اكتشف" },
  "Our Selection": { fr: "Notre sélection", ar: "تشكيلتنا" },
  "From carefully crafted coffee to freshly baked creations, every detail is made to turn an everyday moment into something memorable.": {
    fr: "Du café préparé avec soin aux créations fraîchement sorties du four, chaque détail transforme un instant ordinaire en souvenir précieux.",
    ar: "من القهوة المحضّرة بعناية إلى المخبوزات الطازجة، صُمّم كل تفصيل ليحوّل لحظاتكم اليومية إلى ذكرى مميزة.",
  },
  "At Alarak, every pastry tells a story of dedication, precision, and refined flavor. Our pastry chefs prepare each signature tartlet with fresh berries, delicate custard, and carefully finished chocolate.": {
    fr: "Chez Alarak, chaque pâtisserie raconte une histoire de passion, de précision et de saveurs raffinées. Nos chefs préparent chaque tartelette signature avec des fruits frais, une crème délicate et du chocolat soigneusement travaillé.",
    ar: "في الأراك، تحكي كل قطعة حلوى قصة شغف ودقة ونكهة راقية. يحضّر حلوانيونا تارتاتنا المميزة بالفواكه الطازجة والكاسترد الناعم والشوكولاتة المصقولة بعناية.",
  },
  "Paired with thoughtfully selected specialty coffee, every detail reflects our love of good ingredients and careful craft.": {
    fr: "Accompagné d’un café de spécialité soigneusement sélectionné, chaque détail reflète notre amour des bons ingrédients et du savoir-faire artisanal.",
    ar: "ومع قهوة مختصة مختارة بعناية، يعكس كل تفصيل حبّنا للمكونات الجيدة والحرفة المتقنة.",
  },
  "Visit our location": { fr: "Visiter notre adresse", ar: "زوروا موقعنا" },
  "Tag us at": { fr: "Identifiez-nous sur", ar: "أشيروا إلينا على" },
  "on Instagram to be featured in our community gallery.": { fr: "sur Instagram pour apparaître dans notre galerie.", ar: "على إنستغرام لتظهروا في معرض مجتمعنا." },
  "Your message": { fr: "Votre message", ar: "رسالتك" },
  "Sending...": { fr: "Envoi en cours…", ar: "جارٍ الإرسال…" },
  "Your message has been sent. Thank you!": { fr: "Votre message a bien été envoyé. Merci !", ar: "تم إرسال رسالتك بنجاح، شكراً لك!" },
  "Your message will be sent directly to our team.": { fr: "Votre message sera envoyé directement à notre équipe.", ar: "ستُرسل رسالتك مباشرة إلى فريقنا." },
  "We could not send your message. Please try again.": { fr: "Nous n’avons pas pu envoyer votre message. Veuillez réessayer.", ar: "تعذّر إرسال رسالتك. يُرجى المحاولة مجدداً." },
  "Email is temporarily unavailable. Please contact us on WhatsApp.": { fr: "L’envoi d’e-mail est temporairement indisponible. Contactez-nous sur WhatsApp.", ar: "إرسال البريد الإلكتروني غير متاح مؤقتاً. تواصلوا معنا عبر واتساب." },
  "Your message could not be delivered. Please try again later or contact us on WhatsApp.": { fr: "Votre message n’a pas pu être envoyé. Réessayez plus tard ou contactez-nous sur WhatsApp.", ar: "تعذّر إرسال رسالتك. حاولوا مجدداً لاحقاً أو تواصلوا معنا عبر واتساب." },
  "We could not send your message. Please check your details and try again.": { fr: "Nous n’avons pas pu envoyer votre message. Vérifiez les informations et réessayez.", ar: "تعذّر إرسال رسالتك. تحققوا من المعلومات وحاولوا مجدداً." },
  "Have a question? Send us a note and we'll get back to you.": { fr: "Une question ? Écrivez-nous et nous vous répondrons.", ar: "لديك سؤال؟ أرسل لنا رسالة وسنعاود التواصل معك." },
  "Leave this field empty": { fr: "Laissez ce champ vide", ar: "اترك هذا الحقل فارغاً" },
  "Footer navigation": { fr: "Navigation de pied de page", ar: "روابط أسفل الصفحة" },
  "Legal links": { fr: "Liens juridiques", ar: "روابط قانونية" },
  "Social media links": { fr: "Réseaux sociaux", ar: "روابط التواصل الاجتماعي" },
  "Chat with us on WhatsApp": { fr: "Contactez-nous sur WhatsApp", ar: "تواصلوا معنا عبر واتساب" },
  "Alarak Founder & Master Artisan": { fr: "Fondateur et maître artisan d’Alarak", ar: "مؤسس الأراك وحرفي ماهر" },
  "Alarak artisan berry tartlet, prepared with care": { fr: "Tartelette artisanale aux fruits rouges préparée avec soin", ar: "تارت التوت الحرفي المحضّر بعناية" },
  "Alarak founder welcoming guests": { fr: "Le fondateur d’Alarak accueille ses invités", ar: "مؤسس الأراك يرحّب بالضيوف" },
  "Alarak Coffee & Bakery – Coming Soon": { fr: "Alarak Coffee & Bakery — bientôt", ar: "الأراك للقهوة والمخبوزات — قريباً" },
  "Pistachio vanilla cake on a ceramic plate": { fr: "Gâteau pistache et vanille sur une assiette en céramique", ar: "كعكة بالفستق والفانيليا على طبق خزفي" },
  "Lemon cheesecake slice": { fr: "Part de cheesecake au citron", ar: "قطعة تشيز كيك بالليمون" },
  "Chocolate mousse cake slice": { fr: "Part de gâteau mousse au chocolat", ar: "قطعة كعكة موس الشوكولاتة" },
  "Coffee bean, mango, and strawberry trompe l'œil desserts": { fr: "Desserts trompe-l’œil en forme de grain de café, de mangue et de fraise", ar: "حلويات بتصميم يخدع العين على شكل حبة قهوة ومانجو وفراولة" },
  "Artisan chocolate chip cookies": { fr: "Cookies artisanaux aux pépites de chocolat", ar: "بسكويت حرفي برقائق الشوكولاتة" },
  "Alarak Freshly Baked Pastry": { fr: "Pâtisserie fraîchement préparée chez Alarak", ar: "مخبوزات طازجة من الأراك" },
  "Alarak Signature Pastry": { fr: "Pâtisserie signature d’Alarak", ar: "حلوى الأراك المميزة" },
  "Alarak Fine Dessert": { fr: "Dessert raffiné d’Alarak", ar: "حلوى راقية من الأراك" },
  "Artisan hands preparing fresh pastries on a warm wooden surface": { fr: "Mains d’artisans préparant des pâtisseries fraîches sur un plan de travail en bois", ar: "أيدٍ حرفية تحضّر مخبوزات طازجة على سطح خشبي دافئ" },
  "Specialty latte and artisan pastries beautifully arranged on a café table": { fr: "Latte de spécialité et pâtisseries artisanales joliment disposés sur une table de café", ar: "قهوة لاتيه مختصة ومخبوزات حرفية مرتبة بعناية على طاولة المقهى" },
  "Precision espresso extraction pouring into an Alarak branded cup": { fr: "Extraction précise d’un espresso dans une tasse Alarak", ar: "استخلاص إسبريسو بدقة في فنجان يحمل علامة الأراك" },
  "Exquisite selection of artisan pastries and Moroccan bakery specialties": { fr: "Sélection raffinée de pâtisseries artisanales et de spécialités boulangères marocaines", ar: "تشكيلة فاخرة من الحلويات الحرفية والمخبوزات المغربية المميزة" },
  "Privacy": { fr: "Confidentialité", ar: "الخصوصية" },
  "Terms": { fr: "Conditions générales", ar: "الشروط والأحكام" },
  "All rights reserved.": { fr: "Tous droits réservés.", ar: "جميع الحقوق محفوظة." },
  "© 2026 Alarak Coffee & Bakery": { fr: "© 2026 Alarak Coffee & Bakery", ar: "© 2026 الأراك للقهوة والمخبوزات" },
  "Good Coffee • Great Moments": { fr: "Un bon café • De beaux moments", ar: "قهوة طيبة • لحظات جميلة" },
  "Craft & heartfelt hospitality": { fr: "Savoir-faire et accueil chaleureux", ar: "حرفة أصيلة وضيافة دافئة" },
  "Coffee and pastry are not simply served — they are shared moments of genuine warmth.": {
    fr: "Le café et les pâtisseries ne se servent pas seulement : ils se partagent dans un moment de chaleur sincère.",
    ar: "ليست القهوة والمعجنات مجرد طعام وشراب، بل لحظات دافئة نتشاركها.",
  },
  "08:00 AM – 10:00 PM": { fr: "08 h 00 – 22 h 00", ar: "08:00 – 22:00" },
  "08:00 – 22:00": { fr: "08 h 00 – 22 h 00", ar: "08:00 – 22:00" },
  "Join us in Fnideq for exceptional coffee, fresh pastries, and an atmosphere designed for relaxation.": {
    fr: "Retrouvez-nous à Fnideq pour un café d’exception, des pâtisseries fraîches et une atmosphère propice à la détente.",
    ar: "زورونا في الفنيدق لتستمتعوا بقهوة مميزة ومخبوزات طازجة وأجواء تدعو للاسترخاء.",
  },
  "Specialty coffee and artisan pastry, made slowly in Fnideq — a warm place to pause, savor, and return to.": {
    fr: "Café de spécialité et pâtisseries artisanales préparés avec soin à Fnideq, dans un lieu chaleureux où faire une pause et savourer l’instant.",
    ar: "قهوة مختصة وحلويات يدوية تُحضّر بعناية في الفنيدق، في مكان دافئ للاستراحة والتذوق والعودة إليه.",
  },
  "All": { fr: "Tout", ar: "الكل" },
  "Artisan Coffee": { fr: "Café artisanal", ar: "قهوة حرفية" },
  "Fresh Bakery": { fr: "Boulangerie fraîche", ar: "مخبوزات طازجة" },
  "Interior & Vibe": { fr: "Lieu et ambiance", ar: "المكان والأجواء" },
  "Barista Craft": { fr: "Savoir-faire barista", ar: "إبداع الباريستا" },
  "Signature Pour-Over Precision": { fr: "La précision du café filtre signature", ar: "دقة تحضير القهوة المقطّرة المميزة" },
  "Handcrafted single-origin pour-over coffee brewed with meticulous attention to temperature and grind precision.": { fr: "Un café filtre d’origine unique, préparé à la main avec une attention précise à la température et à la mouture.", ar: "قهوة مقطرة يدوياً من مصدر واحد، تُحضّر بعناية لضبط الحرارة ودرجة الطحن." },
  "Sourced directly from high-altitude Ethiopian farms, our bloom time is timed to the second to unlock delicate floral and bergamot notes.": { fr: "Nos grains viennent de fermes éthiopiennes d’altitude. Une infusion précisément minutée révèle leurs notes florales et de bergamote.", ar: "نختار حبوبنا من مزارع إثيوبية مرتفعة، ونضبط وقت التخمير بدقة لإبراز نكهات الأزهار والبرغموت." },
  "Golden Flake Croissant": { fr: "Croissant doré et feuilleté", ar: "كرواسون ذهبي مورّق" },
  "Freshly baked daily using Normandy butter for 72-hour fermented laminated perfection.": { fr: "Cuit chaque jour au beurre normand, avec une pâte feuilletée fermentée pendant 72 heures.", ar: "يُخبز يومياً بزبدة نورماندي وعجين مورّق مُخمّر لمدة 72 ساعة." },
  "Our master baker begins at 4:00 AM every morning ensuring that classic, shattered-glass crunch on the first bite.": { fr: "Chaque matin dès 4 h, notre chef boulanger prépare ce feuilletage au croustillant incomparable.", ar: "يبدأ خبازنا المحترف عمله يومياً عند الرابعة صباحاً ليمنحكم قرمشة مورّقة من أول لقمة." },
  "Sanctuary of Warmth & Quiet": { fr: "Un refuge de calme et de douceur", ar: "مساحة للدفء والهدوء" },
  "Thoughtfully designed space blending modern Moroccan architecture with warm brass and oak accents.": { fr: "Un espace soigneusement conçu, entre architecture marocaine contemporaine, laiton chaleureux et touches de chêne.", ar: "مساحة مصممة بعناية تجمع العمارة المغربية العصرية بلمسات من النحاس الدافئ وخشب البلوط." },
  "Architecturally crafted to evoke a sense of calm in the heart of Fnideq, offering cozy alcoves and natural sunlight.": { fr: "Au cœur de Fnideq, des alcôves accueillantes et une lumière naturelle créent une atmosphère apaisante.", ar: "في قلب الفنيدق، تمنح الزوايا المريحة والضوء الطبيعي المكان أجواءً هادئة." },
  "Velvet Espresso & Latte Art": { fr: "Espresso velouté et art latte", ar: "إسبريسو مخملي وفن اللاتيه" },
  "Silky microfoam etched with precision over our dark chocolate & hazelnut house espresso blend.": { fr: "Une mousse de lait soyeuse et précise sur notre espresso maison aux notes de chocolat noir et de noisette.", ar: "رغوة حليب ناعمة مرسومة بإتقان فوق إسبريسو الدار بنكهة الشوكولاتة الداكنة والبندق." },
  "Every cup is poured with artistic pride by our senior baristas who train in sensory calibration weekly.": { fr: "Nos baristas expérimentés réalisent chaque tasse avec soin et affinent leurs dégustations chaque semaine.", ar: "يُحضّر خبراء القهوة كل فنجان بإبداع، ويطوّرون حاسة التذوق لديهم أسبوعياً." },
  "Artisan Sourdough & Pastry Display": { fr: "Pain au levain et vitrine de pâtisseries", ar: "خبز العجين المخمّر وتشكيلة المخبوزات" },
  "A daily selection of rustic sourdough loaves, cardamom knots, and seasonal tartlets.": { fr: "Chaque jour, découvrez nos pains au levain, roulés à la cardamome et tartelettes de saison.", ar: "تشكيلة يومية من خبز العجين المخمّر ولفائف الهيل وتارتات الموسم." },
  "Made with wild sourdough starter nurtured in Fnideq since Alarak opened its doors.": { fr: "Notre levain naturel est entretenu à Fnideq depuis l’ouverture d’Alarak.", ar: "نعتني بخميرة العجين الطبيعية في الفنيدق منذ افتتاح الأراك." },
  "Evening Glow at Alarak": { fr: "La lumière du soir chez Alarak", ar: "أجواء الأراك المسائية" },
  "As dusk falls, ambient warm lighting transforms the cafe into an intimate evening retreat.": { fr: "À la tombée du jour, une lumière douce transforme le café en un refuge intime.", ar: "مع حلول المساء، تحوّل الإضاءة الدافئة المقهى إلى مساحة هادئة وحميمة." },
  "Custom dimmable lighting and curated lounge acoustics create the perfect ambiance for evening conversations.": { fr: "Un éclairage réglable et une ambiance sonore soignée accompagnent vos conversations du soir.", ar: "تمنح الإضاءة القابلة للتعديل والأجواء الصوتية الهادئة أمسياتكم طابعاً مثالياً للحديث." },
  "Cold Brew Infusion Tower": { fr: "Tour d’infusion de café à froid", ar: "برج استخلاص القهوة الباردة" },
  "Slow 18-hour Dutch cold drip extraction producing smooth, low-acidity elixir with notes of plum.": { fr: "Une extraction lente de 18 heures, douce et peu acidulée, aux notes de prune.", ar: "استخلاص بارد هولندي بطيء لمدة 18 ساعة، بمذاق ناعم وحموضة خفيفة ونفحات البرقوق." },
  "Extracted drop-by-drop over 18 hours to preserve volatile aromatic compounds without bitterness.": { fr: "Extrait goutte à goutte pendant 18 heures pour préserver ses arômes sans amertume.", ar: "يُستخلص قطرة قطرة على مدى 18 ساعة للحفاظ على عبيره دون مرارة." },
  "Pistachio Paris-Brest": { fr: "Paris-Brest à la pistache", ar: "باريس بريست بالفستق" },
  "Choux pastry ring filled with roasted Sicilian pistachio praline cream and dusted with icing sugar.": { fr: "Une couronne de pâte à choux garnie de praliné à la pistache sicilienne et saupoudrée de sucre glace.", ar: "حلقة من عجينة الشو محشوة بكريمة برالين الفستق الصقلي ومزيّنة بالسكر الناعم." },
  "Our signature homage to classical French patisserie elevated with premium Mediterranean ingredients.": { fr: "Notre hommage à la pâtisserie française classique, sublimé par des ingrédients méditerranéens de qualité.", ar: "تحية من الأراك للحلويات الفرنسية التقليدية، بمكونات متوسطية فاخرة." },
  "Barista Grind Calibration": { fr: "Réglage précis de la mouture", ar: "ضبط طحن القهوة باحتراف" },
  "Dialing in the espresso grind multiple times a day to adapt to humidity and temperature changes.": { fr: "Nous ajustons la mouture de l’espresso plusieurs fois par jour selon l’humidité et la température.", ar: "نضبط درجة طحن الإسبريسو مرات عدة يومياً وفق تغيرات الرطوبة والحرارة." },
  "Consistency is our obsessive standard. Humidity in Fnideq shifts daily, and our grind size adjusts in microns.": { fr: "La régularité est notre exigence : à Fnideq, nous adaptons la mouture au micron près aux variations quotidiennes.", ar: "الثبات معيارنا الدقيق؛ تتغير الرطوبة في الفنيدق يومياً، لذلك نعدّل الطحن بأجزاء دقيقة." },
  "View the menu PDF in a new tab": { fr: "Voir le menu PDF dans un nouvel onglet", ar: "عرض قائمة الطعام بصيغة PDF في علامة تبويب جديدة" },
  "Mediterranean Sea": { fr: "Mer Méditerranée", ar: "البحر الأبيض المتوسط" },
  "Coming Soon": { fr: "Bientôt", ar: "قريباً" },
  "Monday – Sunday": { fr: "Du lundi au dimanche", ar: "من الاثنين إلى الأحد" },
  "Come by,": { fr: "Passez nous voir,", ar: "زورونا،" },
  "Coffee is not just a drink; it’s an invitation to slow down, connect, and savor the finest moments in life.": {
    fr: "Le café n’est pas qu’une boisson : c’est une invitation à ralentir, à se retrouver et à savourer les plus beaux moments de la vie.",
    ar: "القهوة ليست مجرد مشروب؛ إنها دعوة للتمهّل والتواصل والاستمتاع بأجمل لحظات الحياة.",
  },
  "CHAPTER I: ARTISANAL CRAFT": { fr: "CHAPITRE I : SAVOIR-FAIRE ARTISANAL", ar: "الفصل الأول: حرفة أصيلة" },
  "CHAPTER II: COFFEE & PASTRY": { fr: "CHAPITRE II : CAFÉ ET PÂTISSERIE", ar: "الفصل الثاني: القهوة والحلويات" },
  "CHAPTER III: COFFEE EXTRACTION": { fr: "CHAPITRE III : EXTRACTION DU CAFÉ", ar: "الفصل الثالث: استخلاص القهوة" },
  "CHAPTER IV: BAKERY TREASURES": { fr: "CHAPITRE IV : TRÉSORS DE BOULANGERIE", ar: "الفصل الرابع: كنوز المخبوزات" },
  "ALARAK was born from a deep love of craft — where the art of specialty coffee meets the warmth of Moroccan hospitality. Every cup is brewed with intention, every pastry shaped by the hands of artisans who believe that food is a form of care.": {
    fr: "ALARAK est né d’un profond amour du savoir-faire, là où l’art du café de spécialité rencontre la chaleur de l’hospitalité marocaine. Chaque tasse est préparée avec intention et chaque pâtisserie façonnée par des artisans passionnés.",
    ar: "وُلد الأراك من حب عميق للحرفة، حيث يلتقي فن القهوة المختصة بدفء الضيافة المغربية. نحضّر كل فنجان بعناية ونصنع كل حلوى بأيدي حرفيين يؤمنون بأن الطعام شكل من أشكال العناية.",
  },
  "We create spaces and flavors that invite you to slow down, to savor, and to feel genuinely welcomed. This is not just a café — it is a moment worth returning to.": {
    fr: "Nous créons des lieux et des saveurs qui invitent à ralentir, à savourer et à se sentir chaleureusement accueilli. Plus qu’un café, c’est un instant auquel on aime revenir.",
    ar: "نبتكر أماكن ونكهات تدعوك للهدوء والتذوق والشعور بحفاوة الترحيب. ليس مجرد مقهى، بل لحظة تستحق أن نعود إليها.",
  },
  "ALARAK brings contemporary elegance together with the warmth of Moroccan hospitality, creating a welcoming place for coffee lovers and pastry enthusiasts.": {
    fr: "ALARAK unit l’élégance contemporaine à la chaleur de l’hospitalité marocaine pour accueillir les passionnés de café et de pâtisserie.",
    ar: "يجمع الأراك بين الأناقة العصرية ودفء الضيافة المغربية، ليكون مكاناً مرحباً بعشاق القهوة والحلويات.",
  },
  "Whether you’re stopping in for your morning coffee or meeting friends over something sweet, we hope each visit becomes a small ritual worth returning to.": {
    fr: "Que vous passiez pour votre café du matin ou retrouviez des amis autour d’une douceur, nous espérons que chaque visite deviendra un rituel auquel revenir.",
    ar: "سواء مررتم لتناول قهوة الصباح أو للقاء الأصدقاء مع حلوى لذيذة، نأمل أن تصبح كل زيارة عادة جميلة تستحق التكرار.",
  },
});

Object.assign(translations, {
  "A Family Story": { fr: "UNE HISTOIRE DE FAMILLE", ar: "حكاية عائلية" },
  "OUR STORY · NOTRE HISTOIRE": { fr: "NOTRE HISTOIRE", ar: "قصتنا" },
  "Inspired by New York,": { fr: "Inspiré par New York,", ar: "مستوحى من نيويورك،" },
  "Rooted in Morocco": { fr: "Enraciné au Maroc", ar: "متجذر في المغرب" },
  "From New York": { fr: "De New York", ar: "من نيويورك" },
  "to Morocco": { fr: "au Maroc", ar: "إلى المغرب" },
  "Founder & Pastry Artisan": { fr: "Fondateur et artisan pâtissier", ar: "المؤسس وحرفي الحلويات" },
  "Abdellah El Idrissi in a New York restaurant": { fr: "Abdellah El Idrissi dans un restaurant à New York", ar: "عبد الله الإدريسي في مطعم بنيويورك" },
  "New York · Where the journey grew": { fr: "New York · Là où le parcours a grandi", ar: "نيويورك · حيث نمت الرحلة" },
  "The Beginning": { fr: "Les débuts", ar: "البداية" },
  "Craft, curiosity, and a journey across the ocean.": { fr: "Le savoir-faire, la curiosité et un voyage au-delà de l’océan.", ar: "الحرفة والفضول ورحلة عبر المحيط." },
  "Made together": { fr: "Faits ensemble", ar: "صنعناها معاً" },
  "Craft is passed on with joy": { fr: "Le savoir-faire se transmet dans la joie", ar: "الحرفة تنتقل بفرح" },
  "A New Chapter · Morocco": { fr: "Un nouveau chapitre · Maroc", ar: "فصل جديد · المغرب" },
  "A dream shaped around family.": { fr: "Un rêve façonné par la famille.", ar: "حلم صاغته العائلة." },
  "The finest things we make begin with the people we make them for.": { fr: "Nos plus belles créations commencent avec celles et ceux à qui elles sont destinées.", ar: "أجمل ما نصنعه يبدأ من الأشخاص الذين نصنعه من أجلهم." },
  "The El Idrissi Family": { fr: "La famille El Idrissi", ar: "عائلة الإدريسي" },
  "Selected with the same care as everything we bake.": { fr: "Choisi avec autant de soin que tout ce que nous préparons.", ar: "نختارها بعناية ككل ما نخبزه." },
  "Craft is passed on": { fr: "Le savoir-faire se transmet", ar: "الحرفة تنتقل" },
  "with joy": { fr: "avec joie", ar: "بفرح" },
  "From New York to Morocco,": { fr: "De New York au Maroc,", ar: "من نيويورك إلى المغرب،" },
  "a Family Dream Baked Every Day": { fr: "un rêve familial façonné chaque jour", ar: "حلم عائلي يُخبز كل يوم" },
  "A family dream, baked every day.": { fr: "Un rêve familial, préparé chaque jour.", ar: "حلم عائلي نخبزه كل يوم." },
  "Meet Abdellah El Idrissi and the family story behind Alarak Coffee & Bakery.": {
    fr: "Découvrez Abdellah El Idrissi et l’histoire familiale à l’origine d’Alarak Coffee & Bakery.",
    ar: "تعرّفوا على عبد الله الإدريسي وحكاية العائلة وراء الأراك للقهوة والمخبوزات.",
  },
  "My journey into the world of culinary arts and pastry began with a passion for craftsmanship, creativity, and attention to detail. This journey led me to New York, where I earned my diploma from the Institute of Culinary Education in Culinary Arts and Pastry Arts.": {
    fr: "Mon parcours dans les arts culinaires et la pâtisserie est né d’une passion pour le savoir-faire, la créativité et le souci du détail. Il m’a conduit à New York, où j’ai obtenu mon diplôme en arts culinaires et pâtisserie à l’Institute of Culinary Education.",
    ar: "بدأت رحلتي في عالم فنون الطهي والحلويات بشغف للحرفة والإبداع والاهتمام بالتفاصيل. وقادتني هذه الرحلة إلى نيويورك، حيث حصلت على دبلوم في فنون الطهي والحلويات من معهد Institute of Culinary Education.",
  },
  "From New York, I brought back more than techniques. I brought with me a modern approach to the world of coffee, bakery, and pastry — inspired by the diversity, creativity, and energy of the city.": {
    fr: "De New York, j’ai rapporté bien plus que des techniques. J’en ai ramené une approche moderne du café, de la boulangerie et de la pâtisserie, inspirée par la diversité, la créativité et l’énergie de la ville.",
    ar: "عدت من نيويورك بأكثر من مجرد تقنيات؛ جلبت معي رؤية عصرية للقهوة والمخبوزات والحلويات، استلهمتها من تنوع المدينة وإبداعها وحيويتها.",
  },
  "But returning to Morocco marked the beginning of a new chapter.": { fr: "Mais mon retour au Maroc a marqué le début d’un nouveau chapitre.", ar: "لكن عودتي إلى المغرب كانت بداية فصل جديد." },
  "The dream was to transform this experience into something that reflected who we are: a family project built around passion, craftsmanship, and hospitality.": {
    fr: "Le rêve était de transformer cette expérience en un projet à notre image : une aventure familiale portée par la passion, le savoir-faire et l’hospitalité.",
    ar: "كان الحلم أن نحوّل هذه التجربة إلى مشروع يشبهنا: مشروع عائلي يجمعه الشغف والحرفة وحسن الضيافة.",
  },
  "And that dream became Alarak Coffee & Bakery.": { fr: "Et ce rêve est devenu Alarak Coffee & Bakery.", ar: "وهكذا أصبح ذلك الحلم الأراك للقهوة والمخبوزات." },
  "A place where the spirit of New York meets a Moroccan touch, with Mediterranean influences woven into our coffee, pastries, cakes, and baked creations.": {
    fr: "Un lieu où l’esprit de New York rencontre une touche marocaine, tandis que des influences méditerranéennes se glissent dans nos cafés, pâtisseries, gâteaux et créations boulangères.",
    ar: "مكان تلتقي فيه روح نيويورك بلمسة مغربية، وتمتزج التأثيرات المتوسطية بقهوة الأراك ومعجناته وكعكاته ومخبوزاته.",
  },
  "A family craft, shared together": { fr: "Un savoir-faire partagé en famille", ar: "حرفة نتشاركها كأسرة" },
  "Learning, exploring, dreaming": { fr: "Apprendre, découvrir, rêver", ar: "نتعلّم ونكتشف ونحلم" },
  "The joy of making something by hand": { fr: "La joie de créer de ses mains", ar: "فرحة صنع الأشياء بأيدينا" },
  "Abdellah baking together with his daughter": { fr: "Abdellah prépare des pâtisseries avec sa fille", ar: "عبد الله يحضّر المخبوزات مع ابنته" },
  "Abdellah and his daughter outside a New York bakery": { fr: "Abdellah et sa fille devant une boulangerie à New York", ar: "عبد الله وابنته أمام مخبز في نيويورك" },
  "A young family baker presenting a freshly baked pastry": { fr: "Une jeune pâtissière de la famille présente une création fraîchement cuite", ar: "شيف صغيرة من العائلة تقدّم مخبوزاً طازجاً" },
  "Abdellah El Idrissi, founder of Alarak Coffee & Bakery": { fr: "Abdellah El Idrissi, fondateur d’Alarak Coffee & Bakery", ar: "عبد الله الإدريسي، مؤسس الأراك للقهوة والمخبوزات" },
  "Abdellah El Idrissi · Founder": { fr: "Abdellah El Idrissi · Fondateur", ar: "عبد الله الإدريسي · المؤسس" },
  "Our Coffee": { fr: "Notre café", ar: "قهوتنا" },
  "Carefully chosen,": { fr: "Sélectionné avec soin,", ar: "نختاره بعناية،" },
  "thoughtfully served.": { fr: "servi avec attention.", ar: "ونقدّمه باهتمام." },
  "Because coffee is at the heart of the coffee & bakery experience, we carefully selected the coffees we serve.": {
    fr: "Le café étant au cœur de l’expérience coffee & bakery, nous avons soigneusement choisi les cafés que nous servons.",
    ar: "لأن القهوة في قلب تجربة المقهى والمخبوزات، اخترنا بعناية أنواع القهوة التي نقدّمها.",
  },
  "We use Miscela d'Oro Italian coffee, a blend of Arabica and Robusta, alongside illy 100% Arabica, offering different coffee profiles and experiences for our guests.": {
    fr: "Nous servons le café italien Miscela d’Oro, un assemblage d’arabica et de robusta, ainsi que l’illy 100 % arabica, pour offrir à nos clients des profils et des expériences variés.",
    ar: "نقدّم قهوة ميسيلادورو الإيطالية، وهي مزيج من أرابيكا وروبوستا، إلى جانب قهوة illy المصنوعة من أرابيكا 100٪، لنمنح ضيوفنا نكهات وتجارب متنوعة.",
  },
  "For us, quality begins with the ingredients — from the coffee we select to the pastries we bake and the way every creation is prepared and presented.": {
    fr: "Pour nous, la qualité commence par les ingrédients : du café que nous choisissons aux pâtisseries que nous préparons, jusqu’au soin apporté à chaque création et à sa présentation.",
    ar: "تبدأ الجودة عندنا من المكوّنات: من القهوة التي نختارها إلى المخبوزات التي نعدّها، وصولاً إلى طريقة تحضير كل إبداع وتقديمه.",
  },
  "Alarak is more than a Coffee & Bakery.": { fr: "Alarak est plus qu’un café et une boulangerie.", ar: "الأراك أكثر من مقهى ومخبز." },
  "It is a family dream brought to life.": { fr: "C’est un rêve familial devenu réalité.", ar: "إنه حلم عائلي أصبح حقيقة." },
  "Every pastry, every dessert, and every cup of coffee is prepared with care, passion, and a love for the craft.": {
    fr: "Chaque pâtisserie, chaque dessert et chaque tasse de café sont préparés avec soin, passion et amour du métier.",
    ar: "نحضّر كل معجنّة وكل حلوى وكل فنجان قهوة بعناية وشغف وحبّ للحرفة.",
  },
  "Welcome to Alarak.": { fr: "Bienvenue chez Alarak.", ar: "مرحباً بكم في الأراك." },
  "A family dream, baked with passion.": { fr: "Un rêve familial, préparé avec passion.", ar: "حلم عائلي نخبزه بشغف." },
});

Object.assign(translations, {
  "Our Story photos": { fr: "Photos de notre histoire", ar: "صور من حكايتنا" },
  "Choose a story photo": { fr: "Choisir une photo de notre histoire", ar: "اختاروا صورة من حكايتنا" },
  "Show story photo": { fr: "Afficher la photo", ar: "عرض الصورة" },
  "Abdellah preparing pastries in the Alarak kitchen": {
    fr: "Abdellah prépare des pâtisseries dans la cuisine d’Alarak",
    ar: "عبد الله يحضّر الحلويات في مطبخ الأراك",
  },
  "The craft, made by hand": { fr: "Le savoir-faire, façonné à la main", ar: "حرفة تُصنع باليد" },
  "Immeuble Alia, 18, Fnideq 93100": {
    fr: "Immeuble Alia, 18, Fnideq 93100",
    ar: "عمارة علياء، 18، الفنيدق 93100",
  },
  "Open Alarak Coffee & Bakery on Google Maps": {
    fr: "Ouvrir Alarak Coffee & Bakery sur Google Maps",
    ar: "افتحوا موقع الأراك للقهوة والمخبوزات على خرائط جوجل",
  },
  "Coffee": { fr: "Café", ar: "القهوة" },
  "Coffee at Alarak": { fr: "Le café chez Alarak", ar: "القهوة في الأراك" },
  "Our Coffee Selection": { fr: "Notre sélection de cafés", ar: "تشكيلة القهوة لدينا" },
  "Explore our menu": { fr: "Découvrir notre menu", ar: "اكتشفوا قائمتنا" },
  "Menu categories": { fr: "Catégories du menu", ar: "أقسام القائمة" },
  "Coffee is at the heart of our coffee and bakery experience. We carefully select every bean we serve.": {
    fr: "Le café est au cœur de notre expérience coffee & bakery. Nous choisissons avec soin chaque grain que nous servons.",
    ar: "القهوة في قلب تجربة المقهى والمخبوزات لدينا. نختار بعناية كل حبة قهوة نقدمها.",
  },
  "illy coffee bean selection with six varieties": {
    fr: "Sélection de grains de café illy en six variétés",
    ar: "تشكيلة حبوب قهوة illy بستة أنواع",
  },
  "Six origins, six experiences": { fr: "Six origines, six expériences", ar: "ستة أنواع، ست تجارب" },
  "Explore six illy coffee varieties: Classico, Intenso, Decaffeinato, Brasile, Guatemala, and Ethiopia.": {
    fr: "Découvrez six variétés de café illy : Classico, Intenso, Decaffeinato, Brasile, Guatemala et Ethiopia.",
    ar: "اكتشفوا ستة أنواع من قهوة illy: Classico وIntenso وDecaffeinato وBrasile وGuatemala وEthiopia.",
  },
  "illy coffee varieties": { fr: "Variétés de café illy", ar: "أنواع قهوة illy" },
  "Miscela d’Oro Espresso Gran Crema coffee bag": {
    fr: "Paquet de café Miscela d’Oro Espresso Gran Crema",
    ar: "كيس قهوة Miscela d’Oro Espresso Gran Crema",
  },
  "Miscela d’Oro Espresso Gusto Classico coffee bag by the sea": {
    fr: "Paquet de café Miscela d’Oro Espresso Gusto Classico au bord de la mer",
    ar: "كيس قهوة Miscela d’Oro Espresso Gusto Classico بجانب البحر",
  },
  "Italian coffee": { fr: "Café italien", ar: "قهوة إيطالية" },
  "An Italian Arabica and Robusta blend, selected for its full espresso character and velvety crema.": {
    fr: "Un assemblage italien d’arabica et de robusta, choisi pour son espresso intense et sa crema veloutée.",
    ar: "مزيج إيطالي من أرابيكا وروبوستا، اخترناه لمذاق إسبريسو غني وكريمة ناعمة.",
  },
});

const spanishTranslations: Record<string, Partial<Record<Language, string>>> = {
  "Home": { es: "Inicio" },
  "Menu": { es: "Menú" },
  "Our Story": { es: "Nuestra historia" },
  "Gallery": { es: "Galería" },
  "Visit Us": { es: "Visítanos" },
  "View Menu": { es: "Ver menú" },
  "Discover Our Menu": { es: "Descubre nuestro menú" },
  "Moroccan Specialty Coffee & Bakery": { es: "Café de especialidad y panadería marroquí" },
  "Open navigation menu": { es: "Abrir menú de navegación" },
  "Close navigation menu": { es: "Cerrar menú de navegación" },
  "Main Navigation": { es: "Navegación principal" },
  "Select language": { es: "Seleccionar idioma" },
  "Hero Section": { es: "Sección principal" },
  "Where": { es: "Donde" },
  "Elegance": { es: "la elegancia" },
  "Meets Flavor": { es: "se encuentra con el sabor" },
  "Artisan pastries, specialty coffee, and moments worth savoring.": { es: "Repostería artesanal, café de especialidad y momentos para saborear." },
  "Discover Our Story": { es: "Descubre nuestra historia" },
  "OUR STORY": { es: "NUESTRA HISTORIA" },
  "Purpose.": { es: "Con intención." },
  "Crafted with": { es: "Elaborado con" },
  "Made to Be": { es: "Hecho para" },
  "Savored.": { es: "disfrutar." },
  "Signature Selection": { es: "Selección de la casa" },
  "Bakery": { es: "Panadería" },
  "Pastry": { es: "Pastelería" },
  "Desserts": { es: "Postres" },
  "Freshly Baked": { es: "Recién horneado" },
  "Signature Pastries": { es: "Pasteles de la casa" },
  "Fine Desserts": { es: "Postres delicados" },
  "Golden layers and flaky pastries, baked fresh in-house every morning.": { es: "Hojaldres dorados y crujientes, recién horneados cada mañana." },
  "Made slowly. Finished with intention. An elegant touch to your day.": { es: "Preparados con calma y terminados con esmero. Un toque especial para tu día." },
  "A final touch worth staying for — beautiful, seasonal, made with care.": { es: "Un último capricho para disfrutar sin prisa: bonito, de temporada y hecho con cuidado." },
  "Explore": { es: "Descubrir" },
  "View Full Menu": { es: "Ver todo el menú" },
  "Our Menu": { es: "Nuestra carta" },
  "Desserts Menu": { es: "Carta de postres" },
  "A sweeter side of AlArak": { es: "El lado más dulce de Alarak" },
  "Cakes & Pastries": { es: "Tartas y pasteles" },
  "Trompe L'Œil Desserts": { es: "Postres trompe-l’œil" },
  "Cookies": { es: "Galletas" },
  "Coffee": { es: "Café" },
  "Coffee at Alarak": { es: "El café en Alarak" },
  "Our Coffee Selection": { es: "Nuestra selección de café" },
  "Menu categories": { es: "Categorías del menú" },
  "Coffee is at the heart of our coffee and bakery experience. We carefully select every bean we serve.": { es: "El café es el corazón de nuestra experiencia. Seleccionamos cuidadosamente cada grano que servimos." },
  "Six origins, six experiences": { es: "Seis orígenes, seis experiencias" },
  "Italian coffee": { es: "Café italiano" },
  "An Italian Arabica and Robusta blend, selected for its full espresso character and velvety crema.": { es: "Una mezcla italiana de arábica y robusta, elegida por su espresso intenso y su crema aterciopelada." },
  "OUR STORY · NOTRE HISTOIRE": { es: "NUESTRA HISTORIA" },
  "Inspired by New York,": { es: "Inspirados por Nueva York," },
  "Rooted in Morocco": { es: "con raíces en Marruecos" },
  "Founder & Pastry Artisan": { es: "Fundador y maestro pastelero" },
  "New York · Where the journey grew": { es: "Nueva York · Donde comenzó el camino" },
  "The Beginning": { es: "Los comienzos" },
  "My journey into the world of culinary arts and pastry began with a passion for craftsmanship, creativity, and attention to detail.": { es: "Mi camino en las artes culinarias y la pastelería comenzó con pasión por el oficio, la creatividad y la atención al detalle." },
  "This journey led me to New York, where I earned my diploma from the Institute of Culinary Education in Culinary Arts and Pastry Arts.": { es: "Este camino me llevó a Nueva York, donde obtuve mis diplomas en Artes Culinarias y Pastelería en el Institute of Culinary Education." },
  "From New York, I brought back more than techniques. I brought with me a modern approach to the world of coffee, bakery, and pastry — inspired by the diversity, creativity, and energy of the city.": { es: "De Nueva York traje mucho más que técnicas. Me llevé una visión moderna del café, la panadería y la pastelería, inspirada en la diversidad, creatividad y energía de la ciudad." },
  "A New Chapter · Morocco": { es: "Una nueva etapa · Marruecos" },
  "A dream shaped around family.": { es: "Un sueño creado en familia." },
  "But returning to Morocco marked the beginning of a new chapter.": { es: "Pero volver a Marruecos marcó el comienzo de una nueva etapa." },
  "The dream was to transform this experience into something that reflected who we are: a family project built around passion, craftsmanship, and hospitality.": { es: "El sueño era transformar esta experiencia en algo que nos representara: un proyecto familiar basado en la pasión, el oficio y la hospitalidad." },
  "And that dream became": { es: "Y ese sueño se convirtió en" },
  "Alarak Coffee & Bakery.": { es: "Alarak Coffee & Bakery." },
  "A place where the spirit of New York meets a Moroccan touch, with Mediterranean influences woven into our coffee, pastries, cakes, and baked creations.": { es: "Un lugar donde el espíritu de Nueva York se une al toque marroquí, con influencias mediterráneas en nuestros cafés, pasteles y creaciones horneadas." },
  "The finest things we make begin with the people we make them for.": { es: "Las mejores cosas que hacemos nacen pensando en quienes las disfrutan." },
  "The El Idrissi Family": { es: "La familia El Idrissi" },
  "Our Coffee": { es: "Nuestro café" },
  "Selected with the same care as everything we bake.": { es: "Elegido con el mismo cuidado que todo lo que horneamos." },
  "Because coffee is at the heart of the coffee & bakery experience, we carefully selected the coffees we serve.": { es: "Como el café es el corazón de nuestra experiencia, seleccionamos cuidadosamente los cafés que servimos." },
  "We use Miscela d'Oro Italian coffee, a blend of Arabica and Robusta, alongside illy 100% Arabica, offering different coffee profiles and experiences for our guests.": { es: "Servimos café italiano Miscela d’Oro, una mezcla de arábica y robusta, junto con illy 100 % arábica, para ofrecer distintos perfiles y experiencias." },
  "For us, quality begins with the ingredients — from the coffee we select to the pastries we bake and the way every creation is prepared and presented.": { es: "Para nosotros, la calidad empieza con los ingredientes: desde el café que elegimos hasta la preparación y presentación de cada creación." },
  "Made together": { es: "Hecho en familia" },
  "Craft is passed on": { es: "El oficio se transmite" },
  "with joy": { es: "con alegría" },
  "Alarak is more than a Coffee & Bakery.": { es: "Alarak es mucho más que una cafetería y panadería." },
  "It is a family dream brought to life.": { es: "Es un sueño familiar hecho realidad." },
  "Every pastry, every dessert, and every cup of coffee is prepared with care, passion, and a love for the craft.": { es: "Cada pastel, cada postre y cada taza de café se prepara con cuidado, pasión y amor por el oficio." },
  "Welcome to Alarak.": { es: "Te damos la bienvenida a Alarak." },
  "A family dream, baked with passion.": { es: "Un sueño familiar, horneado con pasión." },
  "Location": { es: "Dirección" },
  "Opening Hours": { es: "Horario" },
  "Contact": { es: "Contacto" },
  "Immeuble Alia, 18, Fnideq 93100": { es: "Immeuble Alia, 18, Fnideq 93100" },
  "Monday – Sunday": { es: "Lunes a domingo" },
  "Daily": { es: "Todos los días" },
  "Hours of training": { es: "Horas de formación" },
  "Highest Honors": { es: "Máximos honores" },
  "Graduated with Highest Honors": { es: "Graduado con máximos honores" },
  "Institute of Culinary Education": { es: "Institute of Culinary Education" },
  "CAREER & TRAINING": { es: "TRAYECTORIA Y FORMACIÓN" },
  "From New York, a craft brought home.": { es: "De Nueva York, un oficio que volvió a casa." },
  "Culinary Arts Diploma": { es: "Diploma en Artes Culinarias" },
  "Pastry & Baking Arts Diploma": { es: "Diploma en Pastelería y Panadería" },
  "Culinary Arts · 2016": { es: "Artes Culinarias · 2016" },
  "Pastry & Baking Arts · 2018": { es: "Pastelería y Panadería · 2018" },
  "Our Story photos": { es: "Fotos de nuestra historia" },
  "Choose a story photo": { es: "Elegir una foto de nuestra historia" },
  "Show story photo": { es: "Mostrar foto" },
  "From New York to Morocco,": { es: "De Nueva York a Marruecos," },
  "Explore our menu": { es: "Descubre nuestra carta" },
  "Come share a moment with us.": { es: "Ven a compartir un momento con nosotros." },
  "Good coffee, thoughtful pastries, and a warm welcome in Fnideq.": { es: "Buen café, pasteles artesanales y una cálida bienvenida en Fnideq." },
  "Visit our location": { es: "Visítanos" },
  "Your email address": { es: "Tu correo electrónico" },
  "Your message": { es: "Tu mensaje" },
  "Write your message...": { es: "Escribe tu mensaje..." },
  "Send message": { es: "Enviar mensaje" },
  "Sending...": { es: "Enviando..." },
  "Your message has been sent. Thank you!": { es: "Tu mensaje se ha enviado. ¡Gracias!" },
  "Your message will be sent directly to our team.": { es: "Tu mensaje se enviará directamente a nuestro equipo." },
  "We could not send your message. Please check your details and try again.": { es: "No pudimos enviar tu mensaje. Comprueba tus datos e inténtalo de nuevo." },
  "Email is temporarily unavailable. Please contact us on WhatsApp.": { es: "El correo no está disponible temporalmente. Contáctanos por WhatsApp." },
  "Your message could not be delivered. Please try again later or contact us on WhatsApp.": { es: "No se pudo entregar tu mensaje. Inténtalo más tarde o contáctanos por WhatsApp." },
  "Follow Alarak on Facebook": { es: "Sigue a Alarak en Facebook" },
  "Follow Alarak on TikTok": { es: "Sigue a Alarak en TikTok" },
  "Follow Alarak on Instagram": { es: "Sigue a Alarak en Instagram" },
  "Open Alarak Coffee & Bakery on Google Maps": { es: "Abrir Alarak Coffee & Bakery en Google Maps" },
  "Find us in Fnideq for specialty coffee, freshly baked pastries, and a warm place to pause.": { es: "Visítanos en Fnideq para disfrutar de café de especialidad, pasteles recién hechos y un lugar acogedor." },
  "08:00 – 22:00": { es: "08:00–22:00" },
  "A family dream, baked every day.": { es: "Un sueño familiar, horneado cada día." },
  "A visual journey through artisanal craft, warm ambience, and specialty coffee in Fnideq. Every corner is made for slowing down and savoring the moment.": { es: "Un recorrido visual por la artesanía, el ambiente acogedor y el café de especialidad en Fnideq. Cada rincón invita a bajar el ritmo y disfrutar del momento." },
  "A young family baker presenting a freshly baked pastry": { es: "Una joven integrante de la familia presenta un pastel recién horneado" },
  "ALARAK was born from a deep love of craft — where the art of specialty coffee meets the warmth of Moroccan hospitality. Every cup is brewed with intention, every pastry shaped by the hands of artisans who believe that food is a form of care.": { es: "ALARAK nació de una profunda pasión por el oficio, donde el arte del café de especialidad se une a la calidez de la hospitalidad marroquí. Cada taza se prepara con esmero y cada pastel toma forma de manos artesanas que entienden la cocina como una forma de cuidar." },
  "Abdellah El Idrissi in a New York restaurant": { es: "Abdellah El Idrissi en un restaurante de Nueva York" },
  "Abdellah El Idrissi's pastry and baking arts diploma": { es: "Diploma de pastelería y panadería de Abdellah El Idrissi" },
  "Abdellah and his daughter outside a New York bakery": { es: "Abdellah y su hija frente a una panadería de Nueva York" },
  "Abdellah baking together with his daughter": { es: "Abdellah horneando junto a su hija" },
  "All rights reserved.": { es: "Todos los derechos reservados." },
  "Artisan Mastery in Fnideq": { es: "Maestría artesanal en Fnideq" },
  "Atmosphere & moments": { es: "Ambiente y momentos" },
  "Back to top": { es: "Volver arriba" },
  "Chat with us on WhatsApp": { es: "Escríbenos por WhatsApp" },
  "Coffee and pastry are not simply served — they are shared moments of genuine warmth.": { es: "El café y la pastelería no solo se sirven: se comparten en momentos de auténtica calidez." },
  "Come by,": { es: "Ven a visitarnos," },
  "Come taste it for yourself.": { es: "Ven a probarlo." },
  "Coming Soon": { es: "Próximamente" },
  "Contact Us": { es: "Contáctanos" },
  "Craft & heartfelt hospitality": { es: "Artesanía y hospitalidad sincera" },
  "Crafting Moments of Pure Warmth &": { es: "Creamos momentos de calidez y" },
  "Experience ALARAK In Person": { es: "Vive ALARAK en persona" },
  "Experience Alarak in person": { es: "Vive la experiencia Alarak" },
  "Explore our": { es: "Descubre nuestra" },
  "Fnideq, Morocco": { es: "Fnideq, Marruecos" },
  "Follow": { es: "Síguenos" },
  "Follow Alarak on YouTube": { es: "Sigue a Alarak en YouTube" },
  "Footer navigation": { es: "Navegación del pie de página" },
  "From carefully crafted coffee to freshly baked creations, every detail is made to turn an everyday moment into something memorable.": { es: "Desde el café preparado con esmero hasta cada creación recién horneada, cuidamos cada detalle para convertir un momento cotidiano en algo memorable." },
  "Get Directions": { es: "Cómo llegar" },
  "Good Coffee • Great Moments": { es: "Buen café • Grandes momentos" },
  "Have a question? Send us a note and we'll get back to you.": { es: "¿Tienes alguna pregunta? Escríbenos y te responderemos." },
  "Join us in Fnideq for exceptional coffee, fresh pastries, and an atmosphere designed for relaxation.": { es: "Te esperamos en Fnideq con café excepcional, pasteles recién hechos y un ambiente pensado para relajarse." },
  "Leave this field empty": { es: "Deja este campo vacío" },
  "Legal links": { es: "Enlaces legales" },
  "Next photo": { es: "Foto siguiente" },
  "Our Gallery": { es: "Nuestra galería" },
  "Our Location": { es: "Nuestra ubicación" },
  "Our Selection": { es: "Nuestra selección" },
  "Previous photo": { es: "Foto anterior" },
  "Reservations via Instagram": { es: "Reservas por Instagram" },
  "Send a message": { es: "Envíanos un mensaje" },
  "Social media links": { es: "Enlaces a redes sociales" },
  "Something sweet awaits": { es: "Te espera algo dulce" },
  "Specialty coffee and artisan pastry, made slowly in Fnideq — a warm place to pause, savor, and return to.": { es: "Café de especialidad y pastelería artesanal, elaborados con calma en Fnideq: un lugar acogedor para hacer una pausa, disfrutar y volver." },
  "Tag us at": { es: "Etiquétanos en" },
  "The craft story": { es: "La historia del oficio" },
  "View more about Abdellah's career": { es: "Descubre más sobre la trayectoria de Abdellah" },
  "View on Maps": { es: "Ver en el mapa" },
  "View photo": { es: "Ver foto" },
  "View the menu PDF in a new tab": { es: "Abrir el menú PDF en una pestaña nueva" },
  "Visit & taste": { es: "Visítanos y disfruta" },
  "Visit Alarak →": { es: "Visita Alarak →" },
  "Visit our boutique": { es: "Visita nuestro local" },
  "We create spaces and flavors that invite you to slow down, to savor, and to feel genuinely welcomed. This is not just a café — it is a moment worth returning to.": { es: "Creamos espacios y sabores que invitan a bajar el ritmo, disfrutar y sentirse bienvenido. No es solo una cafetería: es un momento al que apetece volver." },
  "We could not send your message. Please try again.": { es: "No pudimos enviar tu mensaje. Inténtalo de nuevo." },
  "illy coffee bean selection with six varieties": { es: "Selección de granos de café illy con seis variedades" },
  "illy coffee varieties": { es: "Variedades de café illy" },
  "on Instagram to be featured in our community gallery.": { es: "en Instagram para aparecer en nuestra galería comunitaria." },
  "stay awhile.": { es: "quédate un rato." },
  "© 2026 Alarak Coffee & Bakery": { es: "© 2026 Alarak Coffee & Bakery" },
  "Chocolate Mousse Cake": { es: "Tarta de mousse de chocolate" },
  "Carrot Cake": { es: "Tarta de zanahoria" },
  "Tiramisu": { es: "Tiramisú" },
  "Opera Cake": { es: "Tarta Ópera" },
  "Sacher Cake": { es: "Tarta Sacher" },
  "Pistachio Vanilla Cake": { es: "Tarta de pistacho y vainilla" },
  "Rocher Cake": { es: "Tarta Rocher" },
  "Almond Cake": { es: "Tarta de almendra" },
  "Lemon Cheesecake": { es: "Tarta de queso y limón" },
  "Profiteroles": { es: "Profiteroles" },
  "Coffee Bean Trompe L'Œil": { es: "Postre con forma de grano de café" },
  "Mango Trompe L'Œil": { es: "Postre con forma de mango" },
  "Strawberry Trompe L'Œil": { es: "Postre con forma de fresa" },
  "Chocolate Chip Cookie": { es: "Galleta con pepitas de chocolate" },
  "Oat Cookies": { es: "Galletas de avena" },
  "Coconut Cookies": { es: "Galletas de coco" },
  "Cantucci": { es: "Cantucci" },
  "Matcha Cookies": { es: "Galletas de matcha" },
  "Dark Chocolate Cookies": { es: "Galletas de chocolate negro" },
  "Gallery photos": { es: "Fotos de la galería" },
  "Photo coming soon": { es: "Foto próximamente" },
  "Close photo viewer": { es: "Cerrar visor de fotos" },
  "Close viewer": { es: "Cerrar visor" },
  "Share your Alarak moments": { es: "Comparte tus momentos Alarak" },
  "Tag ": { es: "Etiquétanos " },
  "Artisan precision": { es: "Precisión artesanal" },
  "The Art of ": { es: "El arte de " },
  "Slow Crafting": { es: "La elaboración pausada" },
  "Fresh pastries": { es: "Pasteles frescos" },
  "Baked each morning in Fnideq": { es: "Horneados cada mañana en Fnideq" },
  "Specialty coffee": { es: "Café de especialidad" },
  "Single-origin beans, carefully brewed": { es: "Granos de origen único, preparados con esmero" },
  "Handcrafted perfection": { es: "Perfección artesanal" },
  "Fresh berry tartlets, made daily": { es: "Tartaletas de frutos rojos, hechas cada día" },
  "The Alarak philosophy": { es: "La filosofía de Alarak" },
  "Warm hospitality": { es: "Hospitalidad cálida" },
  "A welcome that feels like home": { es: "Una bienvenida que se siente como en casa" },
  "Our vision": { es: "Nuestra visión" },
  "An Elegant Refuge in ": { es: "Un refugio elegante en " },
  "the Heart of Fnideq": { es: "el corazón de Fnideq" },
  "Explore the menu": { es: "Descubre la carta" },
  "Fnideq": { es: "Fnideq" },
  "Morocco": { es: "Marruecos" },
  "Phone": { es: "Teléfono" },
  "We'd love to welcome you to Alarak. Enjoy our coffee, fresh pastries and handcrafted cakes in a warm and relaxed atmosphere.": { es: "Nos encantará recibirte en Alarak. Disfruta de nuestro café, pasteles recién hechos y tartas artesanales en un ambiente cálido y relajado." },
  "Your email app will open with the message ready to send.": { es: "Tu aplicación de correo se abrirá con el mensaje listo para enviar." },
  "Instagram": { es: "Instagram" },
  "Alarak Founder & Master Artisan": { es: "Fundador y maestro artesano de Alarak" },
  "Dessert categories": { es: "Categorías de postres" },
  "Open Fnideq on Google Maps": { es: "Abrir Fnideq en Google Maps" },
  "Whether you're stopping in for your morning coffee or meeting friends over something sweet, we hope each visit becomes a small ritual worth returning to.": { es: "Tanto si vienes por tu café de la mañana como si quedas con amigos para disfrutar de algo dulce, esperamos que cada visita se convierta en un pequeño ritual al que quieras volver." },
  "At the Institute of Culinary Education in New York, Abdellah El Idrissi completed two intensive programs: 720 hours in Culinary Arts, followed by 600 hours in Pastry & Baking Arts. He graduated with Highest Honors in 2016 and 2018, then brought his craft and experience home to Morocco.": { es: "En el Institute of Culinary Education de Nueva York, Abdellah El Idrissi completó dos programas intensivos: 720 horas de Artes Culinarias y 600 horas de Pastelería y Panadería. Se graduó con máximos honores en 2016 y 2018 y después llevó su oficio y experiencia de vuelta a Marruecos." },
  "Graduated with": { es: "Graduado con" },
  "New York, USA": { es: "Nueva York, Estados Unidos" },
  "Total training hours": { es: "Total de horas de formación" },
  "Intensive training in cooking, nutrition, food preparation, and culinary techniques at the Institute of Culinary Education in New York. Graduated with Highest Honors.": { es: "Formación intensiva en cocina, nutrición, preparación de alimentos y técnicas culinarias en el Institute of Culinary Education de Nueva York. Graduado con máximos honores." },
  "Intensive training in pastry, baking, dessert production, and confectionery arts at the Institute of Culinary Education in New York. Graduated with Highest Honors.": { es: "Formación intensiva en pastelería, panadería, elaboración de postres y confitería en el Institute of Culinary Education de Nueva York. Graduado con máximos honores." },
  "Two ICE diplomas": { es: "Dos diplomas del ICE" },
  "Abdellah El Idrissi's culinary arts diploma": { es: "Diploma de Artes Culinarias de Abdellah El Idrissi" },
  "At Alarak, every pastry tells a story of dedication, precision, and refined flavor. Our pastry chefs prepare each signature tartlet with fresh berries, delicate custard, and carefully finished chocolate.": { es: "En Alarak, cada pastel cuenta una historia de dedicación, precisión y sabores refinados. Nuestros pasteleros preparan cada tartaleta de la casa con frutos rojos frescos, crema delicada y chocolate cuidadosamente terminado." },
  "Paired with thoughtfully selected specialty coffee, every detail reflects our love of good ingredients and careful craft.": { es: "Acompañado de café de especialidad cuidadosamente seleccionado, cada detalle refleja nuestro amor por los buenos ingredientes y el trabajo artesanal." },
  "Alarak artisan berry tartlet, prepared with care": { es: "Tartaleta artesanal de frutos rojos de Alarak, preparada con esmero" },
  "Alarak founder welcoming guests": { es: "El fundador de Alarak da la bienvenida a los clientes" },
  "Alarak Coffee & Bakery – Coming Soon": { es: "Alarak Coffee & Bakery – Próximamente" },
  "Pistachio vanilla cake on a ceramic plate": { es: "Tarta de pistacho y vainilla en un plato de cerámica" },
  "Lemon cheesecake slice": { es: "Porción de tarta de queso y limón" },
  "Chocolate mousse cake slice": { es: "Porción de tarta de mousse de chocolate" },
  "Coffee bean, mango, and strawberry trompe l'œil desserts": { es: "Postres con forma de grano de café, mango y fresa" },
  "Artisan chocolate chip cookies": { es: "Galletas artesanales con pepitas de chocolate" },
  "Alarak Freshly Baked Pastry": { es: "Pastelería recién horneada de Alarak" },
  "Alarak Signature Pastry": { es: "Pastelería emblemática de Alarak" },
  "Alarak Fine Dessert": { es: "Postre refinado de Alarak" },
  "Artisan hands preparing fresh pastries on a warm wooden surface": { es: "Manos artesanas preparan pasteles frescos sobre una cálida superficie de madera" },
  "Specialty latte and artisan pastries beautifully arranged on a café table": { es: "Café latte de especialidad y pasteles artesanales dispuestos con esmero en una mesa" },
  "Precision espresso extraction pouring into an Alarak branded cup": { es: "Espresso extraído con precisión y servido en una taza de Alarak" },
  "Exquisite selection of artisan pastries and Moroccan bakery specialties": { es: "Selección exquisita de pasteles artesanales y especialidades marroquíes de panadería" },
  "Privacy": { es: "Privacidad" },
  "Terms": { es: "Condiciones" },
  "08:00 AM – 10:00 PM": { es: "08:00–22:00" },
  "All": { es: "Todo" },
  "Artisan Coffee": { es: "Café artesanal" },
  "Fresh Bakery": { es: "Panadería recién hecha" },
  "Interior & Vibe": { es: "Interior y ambiente" },
  "Barista Craft": { es: "El oficio del barista" },
  "Signature Pour-Over Precision": { es: "Precisión en nuestro café de filtro" },
  "Handcrafted single-origin pour-over coffee brewed with meticulous attention to temperature and grind precision.": { es: "Café de filtro artesanal de origen único, preparado con atención meticulosa a la temperatura y la molienda." },
  "Sourced directly from high-altitude Ethiopian farms, our bloom time is timed to the second to unlock delicate floral and bergamot notes.": { es: "Procedente directamente de fincas etíopes de altura, controlamos el tiempo de preinfusión al segundo para revelar delicadas notas florales y de bergamota." },
  "Golden Flake Croissant": { es: "Cruasán dorado y hojaldrado" },
  "Freshly baked daily using Normandy butter for 72-hour fermented laminated perfection.": { es: "Horneado cada día con mantequilla de Normandía y una fermentación de 72 horas para lograr un hojaldre perfecto." },
  "Our master baker begins at 4:00 AM every morning ensuring that classic, shattered-glass crunch on the first bite.": { es: "Nuestro maestro panadero empieza cada día a las 4:00 para lograr ese crujido ligero y perfecto desde el primer bocado." },
  "Sanctuary of Warmth & Quiet": { es: "Un refugio cálido y tranquilo" },
  "Thoughtfully designed space blending modern Moroccan architecture with warm brass and oak accents.": { es: "Un espacio diseñado con esmero que combina arquitectura marroquí contemporánea con cálidos detalles de latón y roble." },
  "Architecturally crafted to evoke a sense of calm in the heart of Fnideq, offering cozy alcoves and natural sunlight.": { es: "Diseñado para transmitir serenidad en el corazón de Fnideq, con rincones acogedores y luz natural." },
  "Velvet Espresso & Latte Art": { es: "Espresso aterciopelado y arte latte" },
  "Silky microfoam etched with precision over our dark chocolate & hazelnut house espresso blend.": { es: "Microespuma sedosa dibujada con precisión sobre nuestro espresso de la casa con chocolate negro y avellana." },
  "Every cup is poured with artistic pride by our senior baristas who train in sensory calibration weekly.": { es: "Nuestros baristas expertos sirven cada taza con orgullo artístico y perfeccionan semanalmente su calibración sensorial." },
  "Artisan Sourdough & Pastry Display": { es: "Exposición de masa madre y pasteles artesanales" },
  "A daily selection of rustic sourdough loaves, cardamom knots, and seasonal tartlets.": { es: "Una selección diaria de panes rústicos de masa madre, nudos de cardamomo y tartaletas de temporada." },
  "Made with wild sourdough starter nurtured in Fnideq since Alarak opened its doors.": { es: "Elaborados con masa madre natural cuidada en Fnideq desde que Alarak abrió sus puertas." },
  "Evening Glow at Alarak": { es: "El cálido ambiente nocturno de Alarak" },
  "As dusk falls, ambient warm lighting transforms the cafe into an intimate evening retreat.": { es: "Al caer la tarde, la iluminación cálida convierte la cafetería en un refugio íntimo." },
  "Custom dimmable lighting and curated lounge acoustics create the perfect ambiance for evening conversations.": { es: "La iluminación regulable y una acústica cuidada crean el ambiente perfecto para conversar por la noche." },
  "Cold Brew Infusion Tower": { es: "Torre de infusión de café en frío" },
  "Slow 18-hour Dutch cold drip extraction producing smooth, low-acidity elixir with notes of plum.": { es: "Extracción lenta por goteo en frío durante 18 horas para obtener un café suave, de baja acidez y con notas de ciruela." },
  "Extracted drop-by-drop over 18 hours to preserve volatile aromatic compounds without bitterness.": { es: "Extraído gota a gota durante 18 horas para conservar sus aromas sin amargor." },
  "Pistachio Paris-Brest": { es: "Paris-Brest de pistacho" },
  "Choux pastry ring filled with roasted Sicilian pistachio praline cream and dusted with icing sugar.": { es: "Corona de pasta choux rellena de crema de praliné de pistacho siciliano tostado y espolvoreada con azúcar glas." },
  "Our signature homage to classical French patisserie elevated with premium Mediterranean ingredients.": { es: "Nuestro homenaje a la pastelería clásica francesa, realzado con ingredientes mediterráneos de primera calidad." },
  "Barista Grind Calibration": { es: "Ajuste de molienda del barista" },
  "Dialing in the espresso grind multiple times a day to adapt to humidity and temperature changes.": { es: "Ajustamos varias veces al día la molienda del espresso para adaptarnos a los cambios de humedad y temperatura." },
  "Consistency is our obsessive standard. Humidity in Fnideq shifts daily, and our grind size adjusts in microns.": { es: "La constancia es nuestro estándar. Como la humedad en Fnideq cambia cada día, ajustamos la molienda con precisión micrométrica." },
  "Mediterranean Sea": { es: "Mar Mediterráneo" },
  "Coffee is not just a drink; it’s an invitation to slow down, connect, and savor the finest moments in life.": { es: "El café no es solo una bebida: invita a bajar el ritmo, conectar y disfrutar de los mejores momentos de la vida." },
  "CHAPTER I: ARTISANAL CRAFT": { es: "CAPÍTULO I: OFICIO ARTESANAL" },
  "CHAPTER II: COFFEE & PASTRY": { es: "CAPÍTULO II: CAFÉ Y PASTELERÍA" },
  "CHAPTER III: COFFEE EXTRACTION": { es: "CAPÍTULO III: EXTRACCIÓN DEL CAFÉ" },
  "CHAPTER IV: BAKERY TREASURES": { es: "CAPÍTULO IV: TESOROS DE PANADERÍA" },
  "ALARAK brings contemporary elegance together with the warmth of Moroccan hospitality, creating a welcoming place for coffee lovers and pastry enthusiasts.": { es: "ALARAK une la elegancia contemporánea con la calidez de la hospitalidad marroquí y crea un lugar acogedor para amantes del café y la pastelería." },
  "Whether you’re stopping in for your morning coffee or meeting friends over something sweet, we hope each visit becomes a small ritual worth returning to.": { es: "Tanto si vienes por tu café de la mañana como si quedas con amigos para disfrutar de algo dulce, esperamos que cada visita se convierta en un pequeño ritual al que quieras volver." },
  "A Family Story": { es: "Una historia familiar" },
  "From New York": { es: "Desde Nueva York" },
  "to Morocco": { es: "hasta Marruecos" },
  "Craft, curiosity, and a journey across the ocean.": { es: "Oficio, curiosidad y un viaje al otro lado del océano." },
  "Craft is passed on with joy": { es: "El oficio se transmite con alegría" },
  "a Family Dream Baked Every Day": { es: "Un sueño familiar que se hornea cada día" },
  "Meet Abdellah El Idrissi and the family story behind Alarak Coffee & Bakery.": { es: "Conoce a Abdellah El Idrissi y la historia familiar detrás de Alarak Coffee & Bakery." },
  "My journey into the world of culinary arts and pastry began with a passion for craftsmanship, creativity, and attention to detail. This journey led me to New York, where I earned my diploma from the Institute of Culinary Education in Culinary Arts and Pastry Arts.": { es: "Mi camino en el mundo de la cocina y la pastelería comenzó con una pasión por la artesanía, la creatividad y la atención al detalle. Ese camino me llevó a Nueva York, donde obtuve mis diplomas de Artes Culinarias y de Pastelería y Panadería en el Institute of Culinary Education." },
  "And that dream became Alarak Coffee & Bakery.": { es: "Y ese sueño se convirtió en Alarak Coffee & Bakery." },
  "A family craft, shared together": { es: "Un oficio familiar que compartimos" },
  "Learning, exploring, dreaming": { es: "Aprender, explorar y soñar" },
  "The joy of making something by hand": { es: "La alegría de crear algo con las manos" },
  "Abdellah El Idrissi, founder of Alarak Coffee & Bakery": { es: "Abdellah El Idrissi, fundador de Alarak Coffee & Bakery" },
  "Abdellah El Idrissi · Founder": { es: "Abdellah El Idrissi · Fundador" },
  "Carefully chosen,": { es: "Elegido con esmero," },
  "thoughtfully served.": { es: "servido con cuidado." },
  "Abdellah preparing pastries in the Alarak kitchen": { es: "Abdellah prepara pasteles en la cocina de Alarak" },
  "The craft, made by hand": { es: "El oficio, hecho a mano" },
  "Explore six illy coffee varieties: Classico, Intenso, Decaffeinato, Brasile, Guatemala, and Ethiopia.": { es: "Descubre seis variedades de café illy: Classico, Intenso, Decaffeinato, Brasile, Guatemala y Ethiopia." },
  "Miscela d’Oro Espresso Gran Crema coffee bag": { es: "Paquete de café Miscela d’Oro Espresso Gran Crema" },
  "Miscela d’Oro Espresso Gusto Classico coffee bag by the sea": { es: "Paquete de café Miscela d’Oro Espresso Gusto Classico junto al mar" },
};

for (const [key, spanish] of Object.entries(spanishTranslations)) {
  translations[key] = { ...translations[key], ...spanish };
}

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  const setLanguage = useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem("alarak-language", nextLanguage);
  }, []);

  useEffect(() => {
    const saved = window.localStorage.getItem("alarak-language");
    if (saved === "ar" || saved === "en" || saved === "es") setLanguageState(saved);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = useCallback(
    (text: string) => (language === "en" ? text : translations[text]?.[language] ?? text),
    [language]
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
